'use strict';
const type = document.body.dataset.card;
const $ = (s) => document.querySelector(s);
const reduced = window.matchMedia('(prefers-reduced-motion: reduce)').matches;
let sound = false, audio;
function chime(){if(!sound)return;try{audio ||= new (window.AudioContext||window.webkitAudioContext)();audio.resume();[523.25,659.25,783.99].forEach((f,i)=>{const o=audio.createOscillator(),g=audio.createGain(),t=audio.currentTime+i*.11;o.type='sine';o.frequency.value=f;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime(.055,t+.02);g.gain.exponentialRampToValueAtTime(.001,t+.65);o.connect(g);g.connect(audio.destination);o.start(t);o.stop(t+.7);});}catch{sound=false;$('.sound-toggle').textContent='Sound unavailable';$('.sound-toggle').setAttribute('aria-pressed','false');}}
$('.sound-toggle').addEventListener('click',()=>{sound=!sound;$('.sound-toggle').textContent=sound?'Sound on ♫':'Sound off ♫';$('.sound-toggle').setAttribute('aria-pressed',String(sound));chime();});
function burst(symbols=['✦','♡','✿'],amount=48){if(reduced)return;const holder=$('.particles');if(holder.childElementCount>100)return;for(let i=0;i<amount;i++){const el=document.createElement('span');el.className='particle';el.textContent=symbols[i%symbols.length];el.style.cssText=`left:${Math.random()*100}%;color:${['#f5d577','#f39ea9','#83ae87','#fff3bf'][i%4]};--drift:${Math.random()*220-110}px;--spin:${Math.random()*700-350}deg;--duration:${2+Math.random()*2}s;animation-delay:${Math.random()*.7}s;font-size:${12+Math.random()*17}px`;holder.append(el);el.addEventListener('animationend',()=>el.remove(),{once:true});}}
const specks=$('.specks');if(specks)for(let i=0;i<21;i++){const dot=document.createElement('i');dot.className='speck';dot.style.cssText=`left:${5+Math.random()*90}%;top:${36+Math.random()*47}%;--speed:${3+Math.random()*5}s;--delay:-${Math.random()*7}s`;specks.append(dot);}
document.querySelectorAll('dialog').forEach(d=>{d.querySelector('.close-dialog').addEventListener('click',()=>d.close());d.addEventListener('click',e=>{if(e.target===d){const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close();}});});
if(type==='meadow'){
 const pages=[['Dear Jordyn,','Some people make the world feel a little softer, a little brighter, and a lot more like home. You’re one of those people.'],['Here’s to your 24th chapter.','To the belly laughs, the tiny adventures, the “you had to be there” moments. And to all the good things we haven’t even met yet.'],['You’ve got this. And you’ve got me.','You don’t have to have it all figured out at 24. Just keep being wonderfully you. I’m so happy I get to be in your corner. Happy birthday, Jordyn. ♡']];let page=0;
 const show=()=>{$('#letter-title').textContent=pages[page][0];$('#letter-copy').textContent=pages[page][1];$('#letter-count').textContent=`A NOTE FOR YOU · ${page+1} OF 3`;$('#letter-next').textContent=page===2?'Here’s to you, birthday girl ✨':'There’s more →';document.querySelectorAll('.page-dots i').forEach((el,i)=>el.classList.toggle('active',i===page));};
 $('#main-action').addEventListener('click',()=>{page=0;show();$('#letter').showModal();chime();});
 $('#letter-next').addEventListener('click',()=>{chime();if(page<2){page++;show();}else{$('#letter').close();burst();$('.card-bottom>p').textContent='Happy 24th, Jordyn. So loved. Always.';$('#main-action').innerHTML='Read your letter again <span>♡</span>';}});
}
if(type==='frog'){
 const decrees=['All worries are postponed. Cake is a perfectly acceptable breakfast. Your only job is to enjoy being celebrated.','You are officially entitled to spontaneous adventures, ridiculously good snacks, and friendships that feel like sunshine.','Any person in your vicinity must remind you that you’re a delight. The frog insists.','Being 24 does not mean having everything figured out. It does mean being old enough to order the extra fries.','May your confidence be as big as this frog’s crown, and your problems as small as its attention span.','Jordyn, you are deeply loved, wildly appreciated, and absolutely forbidden from forgetting it.'];let decree=0,boop=0,timer;
 function party(){chime();burst(['✷','●','♥','✦'],65);document.body.classList.remove('celebrating');void document.body.offsetWidth;document.body.classList.add('celebrating');$('#party-caption').textContent='Officially 24. Unofficially a national treasure.';}
 $('#main-action').addEventListener('click',()=>{$('#decree-copy').textContent=decrees[decree];$('#decree').showModal();party();});
 $('#next-decree').addEventListener('click',()=>{decree=(decree+1)%decrees.length;$('#decree-copy').textContent=decrees[decree];chime();});
 $('#party-again').addEventListener('click',()=>{$('#decree').close();party();$('#main-action').innerHTML='More royal birthday nonsense <span>✷</span>';});
 $('#frog-boop').addEventListener('click',()=>{const t=$('.frog-toast');t.textContent=['Ribbit. That means “you’re iconic.”','24/10. Would celebrate again.','Small frog. Enormous love.','Birthday queen of the entire pond.'][boop++%4];t.classList.add('show');clearTimeout(timer);timer=setTimeout(()=>t.classList.remove('show'),3000);chime();burst(['♡','✦'],12);});
}
if(type==='garden'){
 const wishes=[['A softer kind of year.','May you give yourself the same gentleness you give everyone else.'],['Big, ridiculous laughter.','The kind that makes your cheeks hurt and turns into an inside joke.'],['Your people, close by.','May there always be someone who says, “Come over. I’ll put the kettle on.”'],['A little bravery.','Enough to try the thing you keep thinking about. You don’t have to feel ready.'],['Ordinary, lovely days.','Sun on your face. A good song. Something delicious. More of those, please.'],['Room to grow.','You’re allowed to become someone new. You’re also allowed to take your time.'],['Unexpected adventures.','The good kind of “well, that wasn’t the plan” — with a story to tell afterwards.'],['A quiet mind.','May the things you cannot control take up a little less space tonight.'],['Dreams with open doors.','Here’s to opportunities that feel like they were waiting just for you.'],['Love that feels easy.','The kind where you never have to wonder if you’re too much.'],['More reasons to dance.','In the kitchen. In the car. Badly, brilliantly, whenever you feel like it.'],['Pride in your own progress.','Even the tiny steps count. Especially the ones nobody else sees.'],['A good surprise.','A message, a moment, a little bit of luck that makes your whole day.'],['Permission to rest.','You don’t have to earn a slow morning or an afternoon doing absolutely nothing.'],['Friendships that stay.','Through new chapters, busy weeks, and all the versions of you to come.'],['A pocketful of courage.','For the hard conversations, the fresh starts, and choosing yourself.'],['Really, really good cake.','This is a birthday wish. We have to cover the essentials.'],['A beautiful new memory.','One you’ll think about years from now and still smile at.'],['Space to be yourself.','No shrinking, no pretending. Just wonderfully, unmistakably Jordyn.'],['Small things to look forward to.','A weekend plan. A favourite meal. A reason to get excited about tomorrow.'],['Trust in your own timing.','Your life isn’t late. Your path is yours. There’s so much still ahead.'],['More sunshine than storms.','And a warm place to land whenever the weather turns.'],['The feeling of being loved.','Not just today. On the boring Tuesdays and the difficult days, too.'],['A magical 24th chapter.','Happy birthday, Jordyn. May this year surprise you in all the loveliest ways. ♡']];
 const found=new Set();let current=0;const field=$('.star-field');
 function showWish(i){current=i;$('#wish-number').textContent=`A WISH FOR JORDYN · ${String(i+1).padStart(2,'0')} / 24`;$('#wish-title').textContent=wishes[i][0];$('#wish-copy').textContent=wishes[i][1];$('#wish-keep').textContent=found.has(i)?'Keep it close ♡':'Keep this little wish ♡';$('#wish').showModal();chime();}
 wishes.forEach((_,i)=>{const star=document.createElement('button');star.className='wish-star';star.textContent=i%3===0?'✧':'✦';star.style.cssText=`--speed:${2+i%4}s;--delay:-${i*.37}s;--offset:${i%2===0?-7:7}px`;star.setAttribute('aria-label',`Open birthday wish ${i+1}`);star.addEventListener('click',()=>showWish(i));field.append(star);});
 $('#main-action').addEventListener('click',()=>{const next=wishes.findIndex((_,i)=>!found.has(i));showWish(next<0?0:next);});
 $('#wish-keep').addEventListener('click',()=>{const fresh=!found.has(current);found.add(current);const star=field.children[current];star.classList.add('found');star.setAttribute('aria-label',`Reopen birthday wish ${current+1}, collected`);$('#wish').close();$('#wish-progress').textContent=`${found.size} of 24 wishes found`;if(fresh){burst(['✦','✧'],14);chime();}if(found.size===24){$('#wish-progress').textContent='24 wishes. One very loved Jordyn.';$('#main-action').innerHTML='Visit your wishes again <span>♡</span>';$('.tiny-note').textContent='May your 24th year hold all this and more.';if(fresh)burst(['✦','♡','✧'],70);}});
}
